
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu May 03 22:26:32 EDT 2012
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int COMPARISON = 17;
  public static final int RPAREN = 7;
  public static final int DOLLAR = 2;
  public static final int STAR = 13;
  public static final int PERIOD = 4;
  public static final int ERROR = 12;
  public static final int NAME = 15;
  public static final int VARIABLE = 18;
  public static final int IMPLIES = 3;
  public static final int LPAREN = 6;
  public static final int LBRACKET = 10;
  public static final int COLON = 8;
  public static final int HASH = 14;
  public static final int RBRACKET = 11;
  public static final int STRING = 16;
  public static final int COMMA = 5;
  public static final int NOTOP = 9;
  public static final int NUMBER = 19;
  public static final int EOF = 0;
  public static final int error = 1;
}

